#!/bin/bash


module swap PrgEnv-cray PrgEnv-gnu
module swap craype-network-ofi craype-network-ucx
module swap cray-mpich cray-mpich-ucx
module load cray-hdf5-parallel/1.12.2.1
module load cray-netcdf-hdf5parallel/4.9.0.1
module load libfabric


module list
export OMP_NUM_THREADS=1

./makenemo -m archer2-gnu-mpich -j 16 -r NAARC_NPD
